server {
    underscores_in_headers on;

    location /check_auth {
        internal;
        proxy_pass_request_body off;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Content-Length "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        client_max_body_size 20M;

        proxy_pass http://auth:4567/api/v1/sessions;
    }

    location /api/v1/sessions {
        proxy_pass http://auth:4567/api/v1/sessions;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        client_max_body_size 20M;
    }

    location /api/v1/users {
        auth_request /check_auth;
        auth_request_set $auth_status $upstream_status;
        error_page 401 = @error401;
        client_max_body_size 20M;

        proxy_pass   http://api:3000/api/v1/users;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location @error401 {
        internal;
        default_type application/json;
        return 401 '{"error": "Unauthorized", "message": "You must be logged in to access this resource."}';
    }
}